name: SurvivalHiveCaptchatheDiamond
main: main\captchatdiamond
version: 1.0
api: 1.12.0
load: STARTUP
author: SurvivalHiveDev
authors: [Xenturio]
description: SurvivalHive CaptchatheDiamond
commands:
 watch:
  description: "Spectator mode"
