name: SurvivalHiveCaptchatheFlag
main: main\captchatheflag
version: 1.0
api: 1.12.0
load: STARTUP
author: SurvivalHiveDev
authors: [Xenturio]
description: SurvivalHive CaptchatheFlag
commands:
 watch:
  description: "Spectator mode"
