name: SurvivalHiveLiftSign
main: main\lift
version: 1.0.0
api: 2.0.0
load: STARTUP
author: SurvivalHiveDev
authors: [Xenturio]
description: Lift sign

permissions:
     survivalhive.lift: 
        default: op #Es gibt op / true / false
        description: "Standard permissions"
