name: SurvivalHivePosition
main: main\pos
version: 1.3
api: 1.4.0
load: STARTUP
author: SurvivalHiveDev
authors: [Xenturio]
description: Position
commands:
 shpos:
  description: "Position auslesen An/Aus"
