name: SurvivalHiveMoney4Kill
main: main\moneyforkill
version: 1.3
api: 2.0.0
load: STARTUP
author: SurvivalHiveDev
authors: [Xenturio]
description: Geld fuers toeten der Spieler
website: http://www.survivalhive.de

