name: SurvivalHiveHungergames
main: main\minigame
version: 1.0
api: 1.12.0
load: STARTUP
author: SurvivalHiveDev
authors: [Xenturio]
description: SurvivalHive Hungergames
commands:
 vote:
  description: "Vote for arena"
 watch:
  description: "Spectator mode"
 playerspawn:
  description: "Playerspawn command"
 chestspawn:
  description: "Chestspawn command"