name: SurvivalHiveRegeln
main: main\regeln
version: 2.0
api: 2.0.0
load: STARTUP
author: SurvivalHiveDev
authors: [Xenturio]
description: Regeln
website: http://www.survivalhive.de
commands:
 regeln:
  description: "Zeigt dir die Regeln an"
 rules:
  description: "Show you the rules"