---
Lobby: lobbyworld
LobbyPos1: 0,0,0
LobbyPos2: "500,150,500"
Arena1: arena1
Arena1Pos1: 0,0,0
Arena1Pos2: "500,150,500"
Arena2: arena2
Arena2Pos1: 0,0,0
Arena2Pos2: "500,150,500"
Arena3: arena3
Arena3Pos1: 0,0,0
Arena3Pos2: "500,150,500"
Arena4: arena4
Arena4Pos1: 0,0,0
Arena4Pos2: "500,150,500"
Arena5: arena5
Arena5Pos1: 0,0,0
Arena5Pos2: "500,150,500"
NumberofChests: "30"
NumberofItemsperChest: "6"
PossibleItemIds:
- 259
- 260
- 261
- 262
- 264
- 265
- 268
- 271
- 272
- 275
- 280
- 282
- 298
- 299
- 300
- 301
- 302
- 303
- 304
- 305
- 306
- 308
- 309
- 314
- 315
- 316
- 317
- 319
- 320
- 354
- 357
- 363
- 364
- 365
- 366
Roundtime: "10"
RandomChestSpawn: true
RandomPlayerSpawn: true
ChestspawnPos: []
PlayerspawnPos: []
ChestspawnPos2: []
PlayerspawnPos2: []
ChestspawnPos3: []
PlayerspawnPos3: []
ChestspawnPos4: []
PlayerspawnPos4: []
ChestspawnPos5: []
PlayerspawnPos5: []
...
